//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fad2.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fad2.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy file {0} of {1}: [{2}] Current Speed:{3:N} {4}.
        /// </summary>
        internal static string CopyFileOfAtSpeed {
            get {
                return ResourceManager.GetString("CopyFileOfAtSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying files....
        /// </summary>
        internal static string CopyingFiles {
            get {
                return ResourceManager.GetString("CopyingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done copying..
        /// </summary>
        internal static string DoneCopying {
            get {
                return ResourceManager.GetString("DoneCopying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s a bit embarrassing .
        /// </summary>
        internal static string ErrorBlameTitle {
            get {
                return ResourceManager.GetString("ErrorBlameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry about this. But it isn&apos;t my fault. Blame Toshiba :).
        /// </summary>
        internal static string ErrorBlameToshiba {
            get {
                return ResourceManager.GetString("ErrorBlameToshiba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed downloading Filelist. Ignore this folder and continue with next one? 
        ///[ignore=continue with next folder, abort=abort all downloads, retry=retry downloading this folder].
        /// </summary>
        internal static string ErrorDownloadingFilelist {
            get {
                return ResourceManager.GetString("ErrorDownloadingFilelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlashAir issues.
        /// </summary>
        internal static string ErrorFlashairGenericTitle {
            get {
                return ResourceManager.GetString("ErrorFlashairGenericTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Settings.
        /// </summary>
        internal static string LoadingSettings {
            get {
                return ResourceManager.GetString("LoadingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading information from files from Flashair at path &apos;{0}&apos;.
        /// </summary>
        internal static string ReadingFlashAirInfoAtPath {
            get {
                return ResourceManager.GetString("ReadingFlashAirInfoAtPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading information from {0} files from Flashair at path &apos;{1}&apos;.
        /// </summary>
        internal static string ReadingInfoFromFilesAtPath {
            get {
                return ResourceManager.GetString("ReadingInfoFromFilesAtPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Thumbnails for Images on Flashair.
        /// </summary>
        internal static string ReadingThumbnailsFromFlashair {
            get {
                return ResourceManager.GetString("ReadingThumbnailsFromFlashair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Thumbnails for Images on Flashair [{0} of {1}].
        /// </summary>
        internal static string ReadingThumnailNo {
            get {
                return ResourceManager.GetString("ReadingThumnailNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading local directory.
        /// </summary>
        internal static string ReadLocalDir {
            get {
                return ResourceManager.GetString("ReadLocalDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done reading File Information from Flashair. Ready to copy new files..
        /// </summary>
        internal static string ReadyToCopy {
            get {
                return ResourceManager.GetString("ReadyToCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Settings.
        /// </summary>
        internal static string SavingSettings {
            get {
                return ResourceManager.GetString("SavingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for File....
        /// </summary>
        internal static string SearchForFile {
            get {
                return ResourceManager.GetString("SearchForFile", resourceCulture);
            }
        }
    }
}
